export const Users = [
  {
    id:1,
    profilePicture: "/images/person_socialmedia/person1.png",
    username: "Manish Gyawali",
  },
  {
    id:2,
    profilePicture: "/images/person_socialmedia/person2.png",
    username: "Sonu G.C.",
  },
  {
    id:3,
    profilePicture: "/images/person_socialmedia/person3.png",
    username: "Kiran Neupane",
  },
  {
    id:4,
    profilePicture: "/images/person_socialmedia/person4.png",
    username: "Kobid Upadhyay",
  },
  {
    id:5,
    profilePicture: "/images/person_socialmedia/person5.png",
    username: "Grishma Khatiwada",
  },
  {
    id:6,
    profilePicture: "/images/person_socialmedia/person6.png",
    username: "Jayanti Dahal",
  },
  {
    id:7,
    profilePicture: "/images/person_socialmedia/person7.png",
    username: "Mohan Gyawali",
  },
  {
    id:8,
    profilePicture: "/images/person_socialmedia/person8.png",
    username: "Sita Gyawali",
  },
  {
    id:9,
    profilePicture: "/images/person_socialmedia/person9.png",
    username: "Sneha Gurung",
  },
  {
    id:10,
    profilePicture: "/images/person_socialmedia/person10.png",
    username: "Rakshya Chhetri",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "/images/images_socialmedia/post1.png",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "/images/images_socialmedia/post2.png",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "/images/images_socialmedia/post3.png",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/images/images_socialmedia/post4.png",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/images/images_socialmedia/post5.png",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/images/images_socialmedia/post6.png",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/images/images_socialmedia/post7.png",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/images/images_socialmedia/post8.png",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "/images/images_socialmedia/post9.png",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "/images/images_socialmedia/post10.png",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
